### ISSUE TITLE
How to open the port.

### ISSUE THREAD

**Issue by Ricardoaraujo00** [sxwei123/dotnet-serialport-demos#1]
Hi,

I came across your repo and ai'm also trying to make a aspnet core program to comunicate with a printer that is connected via usb but expecting serial port comands. In windows i have a virtual com to usb software installed, but that doesn't exists for linux and maybe there is no need of it. 
Listing ports works correctly but when opening an error is thrown:
```
private static void OpenPort()
        {
            try
            {
                // If the port is open, close it.
                Console.WriteLine("Console port is open: " + comport.IsOpen);
                if (!comport.IsOpen)
                {
                    // Set the port's settings
                    comport.BaudRate = int.Parse("9600");
                    comport.DataBits = int.Parse("8");
                    comport.StopBits = StopBits.One;
                    comport.Parity = Parity.None;
                    comport.PortName = "ttyAMA0"; //"COM15";

                    // Open the port
                    comport.Open();
                }
            }
            catch
            {
                Console.WriteLine("Error opening port");
            }
        }
```
I've also tried with "/etc/ttyAMA0" on port name and it doesn't work either.

**Comment by sxwei123** [comment]
@Ricardoaraujo00 You need to make sure your device is supported by the Linux dist you are using. If it is supported, you can find a new file generated by running `ls /etc/tty*`. Its name can be `/etc/ttyACM0`, `/etc/S0` or `/etc/ttyUSB0`. 
Unplug your use device and see which is missing from the list.
